config/routes.rb
require 'subscriber/constraints/subdomain_required'

Subscriber::Engine.routes.draw do
  
  constraints(Subscriber::Constraints::SubdomainRequired) do
    scope :module => "account" do
      root :to => "dashboard#index", :as => :account_root
      get "/sign_in", :to => "sessions#new"
      post "/sign_in", :to => "sessions#create", :as => :sessions

      get "/sign_up", :to => "users#new", :as => :user_sign_up
      post "/sign_up", :to => "users#create", :as => :do_user_sign_up
    end
  end

  root "dashboard#index"

  get "/sign_up", :to => "accounts#new", :as => :sign_up
  post "/accounts", :to => "accounts#create", :as => :accounts
end

app/models/subscriber/account.rb
module Subscriber
  class Account < ActiveRecord::Base
    has_many :members, :class_name => "Subscriber::Member"
    has_many :users, :through => :members
    belongs_to :owner, :class_name => "Subscriber::User"
    accepts_nested_attributes_for :owner

    before_validation do
      self.subdomain = subdomain.to_s.downcase
    end

    validates :subdomain, :presence => true, :uniqueness => true

    validates_format_of :subdomain, :with => /\A[\w\-]+\Z/i,
      :message => "is not allowed. Please choose another subdomain\."

    EXCLUDED_SUBDOMAINS = %w(admin)
    validates_exclusion_of :subdomain, :in => EXCLUDED_SUBDOMAINS,
        :message => "is not allowed. Please choose another subdomain."

    def self.create_with_owner(params={})
      account = new(params)
      if account.save
        account.users << account.owner
      end
      account
      end


  end
end

app/models/subscriber/member.rb
module Subscriber
  class Member < ActiveRecord::Base

    belongs_to :account, :class_name => "Subscriber::Account"
    belongs_to :user, :class_name => "Subscriber::User"
  end
end

app/models/subscriber/user.rb
module Subscriber
  class User < ActiveRecord::Base
    has_secure_password
  end
end

app/controllers/subscriber/account/dashboard_controller.rb
require_dependency "subscriber/application_controller"

module Subscriber
  class Account::DashboardController < Subscriber::ApplicationController
    before_filter :authenticate_user!
  end
end

app/controllers/subscriber/account/sessions_controller.rb
require_dependency "subscriber/application_controller"
module Subscriber
  class Account::SessionsController < ApplicationController

    def new
      @user = User.new
    end

    def create
      if env["warden"].authenticate(:scope => :user)
        flash[:success] = "You are now signed in."
        redirect_to root_path
      else
        @user = User.new
        flash[:error] = "Invalid email or password."
        render :action => "new"
      end
    end


  end
end

app/controllers/subscriber/account/users_controller.rb
require_dependency "subscriber/application_controller"

module Subscriber
  class Account::UsersController < ApplicationController

    def new
      @user = Subscriber::User.new
    end

    def create
      account = Subscriber::Account.find_by_subdomain!(request.subdomain)
      user = account.users.create(user_params)
      force_authentication!(user)
      flash[:success] = "You have signed up successfully."
      redirect_to root_path
    end

    private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end
end

app/controllers/subscriber/accounts_controller.rb
require_dependency "subscriber/application_controller"

module Subscriber
  class AccountsController < ApplicationController

    def new
      @account = Subscriber::Account.new
      @account.build_owner
    end

    def create
      @account = Subscriber::Account.create_with_owner(account_params)

      if @account.valid?

        force_authentication!(@account.owner)

      flash[:success] = "Your account has been successfully created."
      redirect_to subscriber.root_url(:subdomain => @account.subdomain)
      else
        flash[:error] = "Sorry, your account could not be created."
        render :new
      end
    end

  private

      def account_params
        params.require(:account).permit(:name, :subdomain, 
                                        { :owner_attributes => 
                                          [ :email, :password, :password_confirmation ]})
      end
    end
end

app/controllers/subscriber/application_controller.rb
module Subscriber
  class ApplicationController < ::ApplicationController

  end
end

app/controllers/subscriber/dashboard_controller.rb
require_dependency "subscriber/application_controller"

module Subscriber
  class DashboardController < ApplicationController
  end
end

app/helpers/subscriber/account/dashboard_helper.rb
module Subscriber
  module Account::DashboardHelper
  end
end

app/helpers/subscriber/account/sessions_helper.rb
module Subscriber
  module Account::SessionsHelper
  end
end

app/helpers/subscriber/account/users_helper.rb
module Subscriber
  module Account::UsersHelper
  end
end

app/helpers/subscriber/accounts_helper.rb
module Subscriber
  module AccountsHelper
  end
end

app/helpers/subscriber/application_helper.rb
module Subscriber
  module ApplicationHelper
  end
end

app/helpers/subscriber/dashboard_helper.rb
module Subscriber
  module DashboardHelper
  end
end

app/views/layouts/subscriber/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Subscriber</title>
  <%= stylesheet_link_tag    "subscriber/application", media: "all" %>
  <%= javascript_include_tag "subscriber/application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <% flash.each do |k, v| %>
    <div class='flash <%= k  %>'><%= v  %></div>
  <% end %>
  <% if user_signed_in? %>
    Signed in as <%= current_user.email  %>
<% end %>

<%= yield %>

</body>
</html>

app/views/subscriber/account/dashboard/index.html.erb
Your accounts dashboard. Comming soon.

app/views/subscriber/account/users/_form.html.erb
    <p>
      <%= user.label :email  %><br>
      <%= user.email_field :email  %>
    </p>
    <p>
      <%= user.label :password  %><br>
      <%= user.password_field :password  %>
    </p>
    <p>
      <%= user.label :password_confirmation  %>
      <%= user.password_field :password_confirmation  %>
    </p>

app/views/subscriber/account/users/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@user, :url => do_user_sign_up_url) do |user|  %>
  <%= render "subscriber/account/users/form", :user => user  %>
  <%= user.submit "Sign up"  %>
<% end %>

app/views/subscriber/accounts/new.html.erb
<h2>Sign Up</h2>
<%= form_for(@account) do |account|  %>
  <%= account.error_messages  %>
  <p>
    <%= account.label :name  %><br>
    <%= account.text_field :name  %>
  </p>
  <p>
    <%= account.label :subdomain  %><br>
    <%= account.text_field :subdomain  %>
  </p>

  <%= account.fields_for :owner do |owner|  %>
    <%= render "subscriber/account/users/form", :user => owner  %>
  <% end %>

  <%= account.submit  %>
<% end %>

app/views/subscriber/dashboard/index.html.erb
<%= link_to "Account Sign Up", sign_up_path  %>

app/views/things/index.html.erb
<h1>Things</h1>
<ul>
  <% @things.each do |thing| %>
    <li><%= thing.name  %></li>
  <% end %>
</ul>